people:
  - Alice <alice@example.com>
  - Bob <bob@example.com>
  - Carol <carol@example.com>
  - Derek <derek@example.com>
  - Eve <eve@example.com>
  - Frank <frank@example.com>

# Each person in a group cannot give to someone else in the same group.
# This is useful for ensuring, for example, that couples are not assigned
# to each other.
exclusion_groups:
  - [Alice, Bob]
  - [Carol, Derek]
  - [Eve, Frank]

# Mustache template to be used for sending emails
# See README for a list of template variables.
message:
  from: Secret Santa Bot <youremail@example.com>
  subject: Your Secret Santa 2016
  body:
    |
      Dear {{#giver}}{{first_name}}{{/giver}},

      Thanks for being part of our Christmas 2016 Secret Santa.

      Your Secret Santa is: {{#recipient}}{{full_name}}{{/recipient}}.

      Merry Christmas,
      Secret Santa Bot

# Configuration to send email messages
# Use the SMTP configuration for your email server.
email:
  username: secretsanta@example.com
  password: supersecret
  server: mail.example.com
  port: 587
